# Generated by Django 4.2.27 on 2026-02-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_username_profile_picture_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
