# Generated by Django 4.2 on 2026-02-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_user_address_to_useraddress(apps, schema_editor):
    """Copy existing User.address into first UserAddress per user, then remove field."""
    User = apps.get_model("authentication", "User")
    UserAddress = apps.get_model("authentication", "UserAddress")
    for user in User.objects.all():
        addr_text = (getattr(user, "address", None) or "").strip()
        if addr_text:
            UserAddress.objects.create(
                user=user,
                label="Primary",
                street_address=addr_text[:255],
                address_line_2=addr_text[255:510] if len(addr_text) > 255 else "",
                city="",
                state="",
                postal_code="",
                country="",
                is_default=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_user_address_alter_user_username_delete_useraddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, help_text="e.g. Home, Office", max_length=50)),
                ("street_address", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        db_index=True,
                    ),
                ),
            ],
            options={
                "db_table": "auth_user_address",
                "ordering": ["-is_default", "created_at"],
                "verbose_name": "user address",
                "verbose_name_plural": "user addresses",
            },
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(fields=["user", "is_default"], name="auth_user_addr_user_default_idx"),
        ),
        migrations.RunPython(migrate_user_address_to_useraddress, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
    ]
