# Generated by Django 4.2 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_useraddress_remove_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="title",
            field=models.CharField(
                choices=[("HOME", "Home"), ("OFFICE", "Office"), ("OTHER", "Other")],
                db_index=True,
                default="HOME",
                help_text="Address type: Home, Office, or Other",
                max_length=20,
            ),
            preserve_default=True,
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(fields=["user", "title"], name="auth_user_addr_user_title_idx"),
        ),
    ]
