# Generated by Django 4.2.27 on 2026-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_useraddress_title"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="useraddress",
            new_name="auth_user_a_user_id_a9802f_idx",
            old_name="auth_user_addr_user_default_idx",
        ),
        migrations.RenameIndex(
            model_name="useraddress",
            new_name="auth_user_a_user_id_56ce26_idx",
            old_name="auth_user_addr_user_title_idx",
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Optional custom label when title is Other (e.g. Mom's house)",
                max_length=50,
            ),
        ),
    ]
