# Generated by Django 4.2 on 2026-02-24

from django.db import migrations, models


# BD districts for delivery_area choices in migration (same as constants.BD_DISTRICTS).
BD_DISTRICTS_CHOICES = [
    ("Bagerhat", "Bagerhat"), ("Bandarban", "Bandarban"), ("Barguna", "Barguna"),
    ("Barishal", "Barishal"), ("Bhola", "Bhola"), ("Bogura", "Bogura"),
    ("Brahmanbaria", "Brahmanbaria"), ("Chandpur", "Chandpur"),
    ("Chapainawabganj", "Chapainawabganj"), ("Chattogram", "Chattogram"),
    ("Chuadanga", "Chuadanga"), ("Cumilla", "Cumilla"), ("Cox's Bazar", "Cox's Bazar"),
    ("Dhaka", "Dhaka"), ("Dinajpur", "Dinajpur"), ("Faridpur", "Faridpur"),
    ("Feni", "Feni"), ("Gaibandha", "Gaibandha"), ("Gazipur", "Gazipur"),
    ("Gopalganj", "Gopalganj"), ("Habiganj", "Habiganj"), ("Jaipurhat", "Jaipurhat"),
    ("Jamalpur", "Jamalpur"), ("Jashore", "Jashore"), ("Jhalokathi", "Jhalokathi"),
    ("Jhenaidah", "Jhenaidah"), ("Khagrachari", "Khagrachari"), ("Khulna", "Khulna"),
    ("Kishoreganj", "Kishoreganj"), ("Kurigram", "Kurigram"), ("Kushtia", "Kushtia"),
    ("Lalmonirhat", "Lalmonirhat"), ("Laxmipur", "Laxmipur"), ("Madaripur", "Madaripur"),
    ("Magura", "Magura"), ("Manikganj", "Manikganj"), ("Meherpur", "Meherpur"),
    ("Moulvibazar", "Moulvibazar"), ("Munshiganj", "Munshiganj"), ("Mymensingh", "Mymensingh"),
    ("Naogaon", "Naogaon"), ("Narail", "Narail"), ("Narayanganj", "Narayanganj"),
    ("Narsingdi", "Narsingdi"), ("Natore", "Natore"), ("Netrakona", "Netrakona"),
    ("Nilphamari", "Nilphamari"), ("Noakhali", "Noakhali"), ("Pabna", "Pabna"),
    ("Panchagarh", "Panchagarh"), ("Patuakhali", "Patuakhali"), ("Pirojpur", "Pirojpur"),
    ("Rajbari", "Rajbari"), ("Rajshahi", "Rajshahi"), ("Rangamati", "Rangamati"),
    ("Rangpur", "Rangpur"), ("Satkhira", "Satkhira"), ("Shariatpur", "Shariatpur"),
    ("Sherpur", "Sherpur"), ("Sirajganj", "Sirajganj"), ("Sunamganj", "Sunamganj"),
    ("Sylhet", "Sylhet"), ("Tangail", "Tangail"), ("Thakurgaon", "Thakurgaon"),
]


def migrate_address_data(apps, schema_editor):
    UserAddress = apps.get_model("authentication", "UserAddress")
    for addr in UserAddress.objects.all():
        parts = [getattr(addr, "street_address", "") or "", getattr(addr, "address_line_2", "") or "",
                 getattr(addr, "city", "") or "", getattr(addr, "state", "") or "",
                 getattr(addr, "postal_code", "") or "", getattr(addr, "country", "") or ""]
        addr.address = ", ".join(p for p in parts if p).strip() or "N/A"
        title = getattr(addr, "title", "HOME") or "HOME"
        addr.address_type = "HOMETOWN" if title == "OTHER" else title
        addr.delivery_area = getattr(addr, "city", "") or "Dhaka"
        if addr.delivery_area not in [c[0] for c in BD_DISTRICTS_CHOICES]:
            addr.delivery_area = "Dhaka"
        addr.full_name = ""
        addr.phone = ""
        addr.save(update_fields=["address", "address_type", "delivery_area", "full_name", "phone"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_rename_auth_user_addr_user_default_idx_auth_user_a_user_id_a9802f_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="full_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="phone",
            field=models.CharField(default="", max_length=20),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="delivery_area",
            field=models.CharField(
                choices=BD_DISTRICTS_CHOICES,
                default="Dhaka",
                help_text="District (Bangladesh)",
                max_length=50,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="address",
            field=models.TextField(default=""),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name="useraddress",
            name="address_type",
            field=models.CharField(
                choices=[("HOME", "Home"), ("OFFICE", "Office"), ("HOMETOWN", "Hometown")],
                db_index=True,
                default="HOME",
                help_text="Home, Office, or Hometown",
                max_length=20,
            ),
            preserve_default=True,
        ),
        migrations.RunPython(migrate_address_data, noop),
        migrations.RemoveField(model_name="useraddress", name="title"),
        migrations.RemoveField(model_name="useraddress", name="label"),
        migrations.RemoveField(model_name="useraddress", name="street_address"),
        migrations.RemoveField(model_name="useraddress", name="address_line_2"),
        migrations.RemoveField(model_name="useraddress", name="city"),
        migrations.RemoveField(model_name="useraddress", name="state"),
        migrations.RemoveField(model_name="useraddress", name="postal_code"),
        migrations.RemoveField(model_name="useraddress", name="country"),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(fields=["user", "address_type"], name="auth_user_addr_user_atype_idx"),
        ),
    ]
