"""
Cart, checkout, delivery, and payment constants (BDT – Bangladesh).
Aligned with Cart & Checkout, Order Workflow, Payment Logic docs.
"""
from decimal import Decimal

# ---- Cart & Checkout ----
MIN_ORDER_BDT = Decimal("100.00")
FREE_DELIVERY_ABOVE_BDT = Decimal("500.00")
PRICE_LOCK_HOURS = 24

# ---- Delivery (BDT) ----
DELIVERY_ZONE_CITY = "CITY"
DELIVERY_ZONE_SUBURBS = "SUBURBS"
DELIVERY_ZONE_OTHER = "OTHER"
DELIVERY_FEE_CITY_BDT = Decimal("50.00")
DELIVERY_FEE_SUBURBS_BDT = Decimal("100.00")
DELIVERY_FEE_OTHER_BDT = Decimal("150.00")

DELIVERY_FEES = {
    DELIVERY_ZONE_CITY: DELIVERY_FEE_CITY_BDT,
    DELIVERY_ZONE_SUBURBS: DELIVERY_FEE_SUBURBS_BDT,
    DELIVERY_ZONE_OTHER: DELIVERY_FEE_OTHER_BDT,
}

# ---- Payment (MVP Bangladesh) ----
PAYMENT_METHOD_COD = "COD"
PAYMENT_METHOD_BKASH = "BKASH"
PAYMENT_METHOD_NAGAD = "NAGAD"
PAYMENT_METHOD_CHOICES = [
    (PAYMENT_METHOD_COD, "Cash on Delivery"),
    (PAYMENT_METHOD_BKASH, "bKash"),
    (PAYMENT_METHOD_NAGAD, "Nagad"),
]
# Transaction fee (e.g. 0.015 = 1.5%)
PAYMENT_FEE_RATE_COD = Decimal("0")
PAYMENT_FEE_RATE_BKASH = Decimal("0.015")
PAYMENT_FEE_RATE_NAGAD = Decimal("0.015")

PAYMENT_FEE_RATES = {
    PAYMENT_METHOD_COD: PAYMENT_FEE_RATE_COD,
    PAYMENT_METHOD_BKASH: PAYMENT_FEE_RATE_BKASH,
    PAYMENT_METHOD_NAGAD: PAYMENT_FEE_RATE_NAGAD,
}

# ---- Payment transaction status ----
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_INITIATED = "INITIATED"
PAYMENT_STATUS_SUCCESS = "SUCCESS"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_CANCELLED = "CANCELLED"
PAYMENT_STATUS_CHOICES = [
    (PAYMENT_STATUS_PENDING, "Pending"),
    (PAYMENT_STATUS_INITIATED, "Initiated"),
    (PAYMENT_STATUS_SUCCESS, "Success"),
    (PAYMENT_STATUS_FAILED, "Failed"),
    (PAYMENT_STATUS_CANCELLED, "Cancelled"),
]

# ---- Returns ----
RETURN_ALLOWED_DAYS = 7  # Returns allowed within 7 days for unopened items
