# Generated by Django 4.2.27 on 2026-02-06 17:11

from django.db import migrations, models
import django.db.models.deletion


def verified_to_approved(apps, schema_editor):
    Prescription = apps.get_model("core", "Prescription")
    Prescription.objects.filter(status="VERIFIED").update(status="APPROVED")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_catalog_hierarchy'),
    ]

    operations = [
        migrations.RunPython(verified_to_approved, noop),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_prescribed', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'core_prescription_item',
                'ordering': ['product_id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Linked prescription when order contains prescription-only medicines.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_reg_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='has_signature',
            field=models.BooleanField(default=False, help_text='Doctor signature present (set at verification).'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Prescription issue date; must not be older than 6 months.', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name_on_rx',
            field=models.CharField(blank=True, help_text='Patient name as on prescription; must match account holder.', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('USED', 'Used')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['user', 'status'], name='core_prescr_user_id_4e6f9d_idx'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='core.product'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionitem',
            unique_together={('prescription', 'product')},
        ),
    ]
