# Generated by Django 4.2.27 on 2026-02-08 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def order_status_forward(apps, schema_editor):
    Order = apps.get_model("core", "Order")
    Order.objects.filter(status="PENDING").update(status="PLACED")
    Order.objects.filter(status="CONFIRMED").update(status="VERIFIED")
    Order.objects.filter(status="PROCESSING").update(status="PACKED")


def consultation_status_forward(apps, schema_editor):
    Consultation = apps.get_model("core", "Consultation")
    Consultation.objects.filter(status="PENDING").update(status="REQUESTED")
    Consultation.objects.filter(status="CLOSED").update(status="COMPLETED")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_prescription_management_flow'),
    ]

    operations = [
        migrations.RunPython(order_status_forward, noop),
        migrations.RunPython(consultation_status_forward, noop),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_cart',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='consultations/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='specialty',
            field=models.CharField(blank=True, help_text='Optional specialty filter.', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(blank=True, choices=[('CITY', 'City'), ('SUBURBS', 'Suburbs'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('VERIFIED', 'Verified'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLACED', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.order')),
            ],
            options={
                'db_table': 'core_payment_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='core_paymen_order_i_75306c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_locked', models.DecimalField(decimal_places=2, help_text='Price at time of add.', max_digits=12)),
                ('price_locked_until', models.DateTimeField(help_text='Price valid until; recalc after.')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.product')),
            ],
            options={
                'db_table': 'core_cart_item',
                'ordering': ['product_id'],
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
