# Generated by Django 4.2.27 on 2026-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cart_order_payment_consultation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="order",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="consultation",
            name="specialty",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_fee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_zone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.AlterField(
            model_name="consultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("PROCESSING", "Processing"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="PaymentTransaction",
        ),
    ]
