# Generated by Django 4.2.27 on 2026-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cart_cartitem_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, help_text="Strength e.g. '50mg', '500mg', '5ml' for display and dosage selection.", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='key_benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of benefit strings for Description tab bullet points.'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP / list price for showing crossed-out price and discount percentage.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating 0–5 for display (e.g. 5.0).', max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text="Number of reviews (e.g. for '1.2k+ Reviews')."),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pairs for Specification tab (e.g. {'Dosage Form': 'Oral Tablet'})."),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_label',
            field=models.CharField(blank=True, help_text="e.g. '10 Tablets (1 Strip)', '20 Tablets (2 Strip)'.", max_length=120),
        ),
    ]
