# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_pricing_dosage_ratings_specs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sidebar/%Y/%m/')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_sidebar_category',
                'ordering': ['id'],
                'verbose_name_plural': 'Sidebar categories',
            },
        ),
    ]
