# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sidebar_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/%Y/%m/')),
                ('link', models.URLField(blank=True, help_text='Destination URL when ad is clicked.', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order; lower first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_ad',
                'ordering': ['order', 'id'],
                'verbose_name_plural': 'Ads',
            },
        ),
    ]
