# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_label', models.CharField(help_text="Strength e.g. '50mg', '500mg', '5ml'.", max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order; lower first.')),
                ('product', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_options', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Product dosages',
                'db_table': 'core_product_dosage',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productdosage',
            constraint=models.UniqueConstraint(fields=('product', 'dosage_label'), name='core_product_dosage_product_dosage_label_uniq'),
        ),
    ]
