# Generated by Django 4.2.28 on 2026-03-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_dosage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productdosage',
            name='core_product_dosage_product_dosage_label_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='productdosage',
            unique_together={('product', 'dosage_label')},
        ),
    ]
