# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='dosage',
            field=models.CharField(blank=True, help_text="Selected dosage for this line (e.g. 50mg, 500mg).", max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dosage',
            field=models.CharField(blank=True, help_text="Selected dosage for this line (e.g. 50mg, 500mg).", max_length=50),
        ),
    ]
