# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_cartitem_orderitem_dosage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="combos/%Y/%m/")),
                ("link", models.URLField(blank=True, help_text="Destination URL when combo card is clicked (e.g. product list or CMS page).", max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("original_price", models.DecimalField(blank=True, decimal_places=2, help_text="Optional struck-through price for showing discount on combo.", max_digits=12, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0, help_text="Display order; lower first.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Combos",
                "db_table": "core_combo",
                "ordering": ["order", "id"],
            },
        ),
    ]

