# Generated by Django 4.2.28 on 2026-03-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cartitem_orderitem_dosage'),
        ('core', '0012_remove_productdosage_core_product_dosage_product_dosage_label_uniq_and_more'),
    ]

    operations = [
    ]
