# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_combo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLogo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(db_index=True, help_text="Identifier for where the logo is used (e.g. 'header', 'footer').", max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="logos/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "App logos",
                "db_table": "core_app_logo",
                "ordering": ["slug"],
            },
        ),
    ]

