# Generated by Django 4.2.28 on 2026-03-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20260308_1956'),
        ('core', '0014_applogo'),
    ]

    operations = [
    ]
