# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_applogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="bg_color",
            field=models.CharField(
                max_length=32,
                blank=True,
                help_text="Optional background color for combo card (e.g. hex code or Tailwind class).",
            ),
        ),
    ]

