# Generated by Django 4.2.27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_combo_bg_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField(help_text="Rating 1–5.")),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="core.product")),
                ("user", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="product_reviews", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "Product reviews",
                "db_table": "core_product_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReviewImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="reviews/%Y/%m/")),
                ("order", models.PositiveSmallIntegerField(default=0, help_text="Display order; lower first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("review", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="images", to="core.productreview")),
            ],
            options={
                "db_table": "core_product_review_image",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(fields=("user", "product"), name="core_product_review_user_product_uniq"),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["product"], name="core_product_product_idx"),
        ),
    ]
