# Generated by Django 4.2.28 on 2026-03-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_combo_bg_color'),
        ('core', '0015_merge_0013_merge_20260308_1956_0014_applogo'),
    ]

    operations = [
    ]
