# Generated by Django 4.2.28 on 2026-03-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20260314_0101'),
        ('core', '0016_product_review'),
    ]

    operations = [
    ]
