# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryDuration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="e.g. Standard 3–5 days", max_length=100)),
                ("days", models.PositiveSmallIntegerField(blank=True, help_text="Optional number of days for display.", null=True)),
                ("order", models.PositiveSmallIntegerField(default=0, help_text="Display order; lower first.")),
            ],
            options={
                "db_table": "core_delivery_duration",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="duration",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text="Expected delivery duration (admin can set).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.deliveryduration",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.TextField(blank=True, help_text="Customer message with the order."),
        ),
        migrations.CreateModel(
            name="OrderImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="orders/%Y/%m/")),
                ("order_display", models.PositiveSmallIntegerField(default=0, help_text="Display order; lower first.")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "db_table": "core_order_image",
                "ordering": ["order_display", "id"],
            },
        ),
    ]
