# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


def backfill_order_status_history(apps, schema_editor):
    Order = apps.get_model("core", "Order")
    OrderStatusHistory = apps.get_model("core", "OrderStatusHistory")
    for order in Order.objects.all():
        OrderStatusHistory.objects.create(
            order=order,
            status=order.status,
            created_at=order.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_order_images_duration_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "db_table": "core_order_status_history",
                "ordering": ["created_at"],
                "verbose_name_plural": "Order status history",
            },
        ),
        migrations.RunPython(backfill_order_status_history, migrations.RunPython.noop),
    ]

