# Generated by Django 4.2.28 on 2026-03-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_0016_merge_20260314_0101_0016_product_review'),
        ('core', '0019_order_status_history'),
    ]

    operations = [
    ]
