# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_order_status_history"),
        ("authentication", "0013_rename_delivery_area_to_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected shipping address for this prescription order.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescription_orders",
                to="authentication.useraddress",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="save_prescription",
            field=models.BooleanField(default=False, help_text="Save prescription for future reference/reorder."),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicine_supply_duration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("7_DAYS", "7 Days"),
                    ("15_DAYS", "15 Days"),
                    ("1_MONTH", "1 Month"),
                    ("2_MONTHS", "2 Months"),
                    ("CUSTOM", "Custom"),
                ],
                db_index=True,
                help_text="7 Days, 15 Days, 1 Month, 2 Months, or Custom.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="custom_supply_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="When medicine_supply_duration is CUSTOM, number of days.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescription_note",
            field=models.TextField(blank=True, help_text="User note for the uploading prescription."),
        ),
        migrations.AddField(
            model_name="prescription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PrescriptionImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="prescriptions/%Y/%m/")),
                ("order_display", models.PositiveSmallIntegerField(default=0, help_text="Display order; lower first.")),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "core_prescription_image",
                "ordering": ["order_display", "id"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.prescription",
                    ),
                ),
            ],
            options={
                "db_table": "core_prescription_status_history",
                "ordering": ["created_at"],
                "verbose_name_plural": "Prescription status history",
            },
        ),
    ]

