# Generated by Django 4.2.27

from django.db import migrations


def backfill_prescription_status_history(apps, schema_editor):
    Prescription = apps.get_model("core", "Prescription")
    PrescriptionStatusHistory = apps.get_model("core", "PrescriptionStatusHistory")
    for rx in Prescription.objects.all():
        PrescriptionStatusHistory.objects.create(
            prescription=rx,
            status=rx.status,
            created_at=rx.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_prescription_ordering"),
    ]

    operations = [
        migrations.RunPython(backfill_prescription_status_history, migrations.RunPython.noop),
    ]
