# Generated by Django 4.2.28 on 2026-03-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20260315_0046'),
        ('core', '0021_backfill_prescription_status_history'),
    ]

    operations = [
    ]
