# Generated by Django 4.2.27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_backfill_prescription_status_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="additional_products_note",
            field=models.TextField(
                blank=True,
                help_text="Optional note about additional products the user wants with this prescription.",
            ),
        ),
    ]

