# Generated by Django 4.2.28 on 2026-03-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20260316_0850'),
        ('core', '0022_prescription_additional_products_note'),
    ]

    operations = [
    ]
