# Generated by Django 4.2.27

from django.db import migrations, models
import django.db.models.deletion


def backfill_original_price_at_order(apps, schema_editor):
    CartItem = apps.get_model("core", "CartItem")
    for item in CartItem.objects.all():
        if item.original_price_at_order is None:
            item.original_price_at_order = item.price_at_order
            item.save(update_fields=["original_price_at_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_prescription_additional_products_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text="Applied coupon for this cart (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="core.coupon",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="original_price_at_order",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Locked unit price at add-to-cart before any coupon discount is applied.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.RunPython(backfill_original_price_at_order, migrations.RunPython.noop),
    ]

