# Generated by Django 4.2.28 on 2026-03-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_cart_coupon_persist_discount'),
        ('core', '0023_merge_20260316_1750'),
    ]

    operations = [
    ]
