# Generated by Django 4.2.28 on 2026-03-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20260317_1449'),
        ('core', '0024_order_discount_breakdown'),
    ]

    operations = [
    ]
