# Generated by Django 4.2.28 on 2026-04-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20260317_1649'),
        ('core', '0026_user_notification'),
    ]

    operations = [
    ]
