# Generated by Django 4.2.29 on 2026-04-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_payment_transaction_sslcommerz"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("browser_permission", models.CharField(choices=[("default", "Default"), ("granted", "Granted"), ("denied", "Denied")], db_index=True, default="default", max_length=20)),
                ("is_enabled", models.BooleanField(db_index=True, default=False, help_text="True when user granted permission and wants push/browser notifications.")),
                ("last_prompted_at", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="notification_preference", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "core_user_notification_preference",
                "ordering": ["-updated_at"],
            },
        ),
    ]
