# Generated by Django 4.2.27 on 2026-04-15 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0036_user_push_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productreview',
            name='core_product_review_user_product_uniq',
        ),
        migrations.RenameIndex(
            model_name='b2bcommissionentry',
            new_name='core_b2b_co_custome_68e9b9_idx',
            old_name='core_b2b__custome_6d5caa_idx',
        ),
        migrations.RenameIndex(
            model_name='b2bcommissionentry',
            new_name='core_b2b_co_order_i_9e7fc3_idx',
            old_name='core_b2b__order_i_6e2d29_idx',
        ),
        migrations.RenameIndex(
            model_name='blogpost',
            new_name='core_blog_p_categor_20f96d_idx',
            old_name='core_blog_p_categor_16b55f_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersettlement',
            new_name='core_order__status_aea5a9_idx',
            old_name='core_order__status__c_2b3b87_idx',
        ),
        migrations.RenameIndex(
            model_name='ordersettlement',
            new_name='core_order__payment_8af595_idx',
            old_name='core_order__paymen_f73bb7_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='core_produc_product_7904fe_idx',
            old_name='core_product_product_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='core_user_n_user_id_ac6eed_idx',
            old_name='core_user_n_user_id_f4fdb3_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='core_user_n_user_id_bb1e69_idx',
            old_name='core_user_n_user_id_55321b_idx',
        ),
        migrations.RenameIndex(
            model_name='userpushsubscription',
            new_name='core_user_p_user_id_fa54a5_idx',
            old_name='core_user_p_user_id_2d704d_idx',
        ),
        migrations.RenameIndex(
            model_name='userpushsubscription',
            new_name='core_user_p_user_id_0161fd_idx',
            old_name='core_user_p_user_id_2a4d93_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total payable (after discount + delivery fee).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal admin notes.'),
        ),
        migrations.AlterField(
            model_name='prescriptionstatushistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('USED', 'Used')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userpushsubscription',
            name='endpoint',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('user', 'product')},
        ),
    ]
