# Generated by Django 4.2.27 on 2026-04-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_userpushsubscription_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Home featured display order; lower values appear first.'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured_home',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, this category is shown in home featured categories.'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_sidebar',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, this category is shown in the public sidebar menu.'),
        ),
        migrations.AddField(
            model_name='category',
            name='sidebar_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Sidebar display order; lower values appear first.'),
        ),
    ]
