# Generated by Django 4.2.27 on 2026-04-18 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_category_sidebar_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_url', models.URLField(blank=True, max_length=500)),
                ('audience_mode', models.CharField(choices=[('ALL_ACTIVE', 'All active users'), ('OPTED_IN_ONLY', 'Opted-in users only'), ('USER_IDS', 'Specific user ids'), ('ROLE_BASED', 'Role-based segment')], db_index=True, default='ALL_ACTIVE', max_length=32)),
                ('source', models.CharField(default='admin', help_text='Origin of this campaign: admin, order_event, prescription_event, payment_event, etc.', max_length=40)),
                ('role_filter', models.CharField(blank=True, help_text='Optional role when audience_mode=ROLE_BASED.', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('PARTIAL', 'Partially delivered'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Optional idempotency key for event-driven notifications.', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('push_attempted', models.PositiveIntegerField(default=0)),
                ('push_succeeded', models.PositiveIntegerField(default=0)),
                ('push_failed', models.PositiveIntegerField(default=0)),
                ('push_deactivated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_notification_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usernotification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.notificationcampaign'),
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DEACTIVATED', 'Token deactivated')], db_index=True, max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('permanent_failure', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='core.notificationcampaign')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='core.userpushsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_notification_delivery_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='core_notifi_campaig_7c1d74_idx'), models.Index(fields=['user', 'created_at'], name='core_notifi_user_id_d09988_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['status', 'created_at'], name='core_notifi_status_643099_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['audience_mode', 'created_at'], name='core_notifi_audienc_2bbc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationcampaign',
            index=models.Index(fields=['source', 'created_at'], name='core_notifi_source_8fe674_idx'),
        ),
    ]
