# Generated by Django 4.2.27 on 2026-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_notificationcampaign_usernotification_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternative_products',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_administration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='drug_classes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='faq',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='indications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='interaction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mode_of_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='overdose_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='precautions_warnings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pregnancy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pregnancy_lactation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='therapeutic_class',
            field=models.TextField(blank=True),
        ),
    ]
