# Generated by Django 4.2.30 on 2026-04-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_type', 'content_type', 'quantity']},
        ),
        migrations.AddField(
            model_name='unit',
            name='content_type',
            field=models.CharField(default='Tablets', help_text="What the package contains e.g. 'Tablets', 'Capsules', 'ml Syrup', 'gm Cream'.", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='quantity',
            field=models.PositiveIntegerField(default=10, help_text='Number of items or volume e.g. 10, 20, 80.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(default='Strip', help_text="Packaging type e.g. 'Strip', 'Bottle', 'Vial', 'Box', 'Tube', 'Sachet'.", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unit_type', 'content_type', 'quantity')},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='name',
        ),
    ]
