# Generated by Django 4.2.30 on 2026-04-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_unit_options_unit_content_type_unit_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_label',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, help_text="Packaging unit e.g. 'Strip of 10 Tablets'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.unit'),
        ),
    ]
