# Generated by Django 4.2.27 on 2026-05-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_product_unit_label_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_home_categoery',
            field=models.BooleanField(db_index=True, default=False, help_text='Additional boolean field for home category (per user request).'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_homepage',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this product in the homepage featured section.'),
        ),
    ]
