# Generated by Django 4.2.27 on 2026-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_category_is_home_categoery_product_is_in_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='link',
        ),
        migrations.AddField(
            model_name='combo',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Select products for this combo.', related_name='combos', to='core.product'),
        ),
    ]
