# Generated by Django 4.2.27 on 2026-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_combo_link_combo_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='forth_section',
            field=models.BooleanField(db_index=True, default=False, help_text='When true, this category is shown in the forth section.'),
        ),
    ]
