# Generated by Django 4.2.27 on 2026-05-18 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_category_forth_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard Delivery', max_length=100)),
                ('delivery_type', models.CharField(choices=[('STANDARD', 'Standard Delivery'), ('SAME_DAY', 'Same Day Delivery'), ('EXPRESS', 'Express Delivery')], db_index=True, default='STANDARD', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Base amount for this delivery method.', max_digits=12)),
                ('duration', models.CharField(blank=True, help_text="Expected delivery duration (e.g., '2-3 days', '24 hours').", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Final price/charge applied to the order.', max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order; lower first.')),
            ],
            options={
                'db_table': 'core_delivery_method',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='delivery_duration_id_ref',
            new_name='delivery_method_id_ref',
        ),
        migrations.RemoveField(
            model_name='order',
            name='duration',
        ),
        migrations.DeleteModel(
            name='DeliveryDuration',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, help_text='Selected delivery method.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.deliverymethod'),
        ),
    ]
