# Generated by Django 4.2.27 on 2026-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
