# Generated by Django 4.2.27 on 2026-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_order_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
