# Generated by Django 4.2.27 on 2026-05-25 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_prescription_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.combo'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', False), ('combo__isnull', True)), models.Q(('product__isnull', True), ('combo__isnull', False)), _connector='OR'), name='cart_item_exactly_one_product_or_combo'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'combo'), ('cart', 'product')},
        ),
    ]
