# Generated by Django 4.2.27 on 2026-05-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_orderitem_unique_together_orderitem_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin-set fixed price for the whole combo bundle. Overrides product sum for cart if no discount_price.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set, this is the effective sale price used for CartItem.price_at_order (and thus charged at checkout). Takes highest precedence.', max_digits=12, null=True),
        ),
    ]
